name: CI / CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run tests
        run: |
          go test ./...
          go vet ./...

  build-and-deploy:
    name: Build and optionally deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository }}:latest .

      # Optional: deploy to Cloud Run if the GCP SA key and project are configured
      - name: Authenticate to GCP
        if: ${{ secrets.GCP_SA_KEY != '' && secrets.GCP_PROJECT != '' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        if: ${{ secrets.GCP_SA_KEY != '' && secrets.GCP_PROJECT != '' && secrets.CLOUD_RUN_SERVICE != '' && secrets.CLOUD_RUN_REGION != '' }}
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ secrets.CLOUD_RUN_SERVICE }}
          image: ${{ github.repository }}:latest
          region: ${{ secrets.CLOUD_RUN_REGION }}
          project_id: ${{ secrets.GCP_PROJECT }}
